services:
  nats:
    image: nats:2.11-alpine
    container_name: hydra-dev-nats
    ports:
      - "4222:4222"    # NATS client port (same as HYDRA production)
      - "6222:6222"    # Cluster port (for completeness)
      - "8222:8222"    # HTTP monitoring (development only)
    volumes:
      - "./nats/nats-server.conf:/etc/nats/nats-server.conf:ro"
    command: ["-c", "/etc/nats/nats-server.conf"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - hydra-dev
    # Removed user directive - not needed without file logging

  # Optional: NATS monitoring UI for development
  nats-surveyor:
    image: natsio/nats-surveyor:latest
    container_name: hydra-dev-monitor
    ports:
      - "7777:7777"    # Monitoring dashboard
    environment:
      - NATS_SURVEYOR_SERVER_COUNT=1
      - NATS_SURVEYOR_SERVERS=nats://nats:4222
    depends_on:
      nats:
        condition: service_healthy
    networks:
      - hydra-dev
    profiles:
      - monitoring

networks:
  hydra-dev:
    driver: bridge
